version: '3'

# Assumes the existence of an .env file

services:
  ftpd_server:
    image: local/pure-ftpd
    container_name: pure-ftpd
    restart: 'no'
    environment:
      PURE_FTPD_PASSIVE_IP: "${PURE_FTPD_PASSIVE_IP}"
# E.g. PURE_FTPD_PASSIVE_PORTS=n:m in .env
      PURE_FTPD_PASSIVE_PORTS: "${PURE_FTPD_PASSIVE_PORTS}"
      PURE_FTPD_CUSTOM_FLAGS: "${PURE_FTPD_CUSTOM_FLAGS}"
# Uncomment if creation of ftp user is wanted
#      FTP_USER_NAME: ftp
#      FTP_USER_PASS: ftp-user-password
#      FTP_USER_HOME: /home/ftp
    ports:
      - "${PURE_FTPD_BIND_PORT}:${PURE_FTPD_BIND_PORT}"
# E.g PURE_FTPD_PASSIVE_PORT_RANGE=n-m in .env
      - "${PURE_FTPD_PASSIVE_PORT_RANGE}:${PURE_FTPD_PASSIVE_PORT_RANGE}"
    volumes:
# Uncomment for a pre-existing passwd file - should contain pureftpd.passwd
#      - type: bind
#        source: conf/passwd
#        target: /etc/pure-ftpd/passwd
# Uncomment for a pre-existing puredb file (overrides passwd file) -- should contain pureftpd.pdb
#      - type: bind
#        source: conf/puredb
#        target: /etc/pure-ftpd/puredb
# Uncomment for pre-existing certificate file(s) - should contain pure-ftpd.pem
#      - type: bind
#        source: conf/ssl
#        target: /etc/ssl/private

# Additional volumes
#      - /folder_on_disk/data:/home/ftp:rw
